# Tomcat: http://localhost:8080/sportscarshop/
# App -> /api
# CartService -> /cart

# CRUD

# ADD sukuriamas tuščias krepšelis
POST http://localhost:8080/sportscarshop/api/cart
Content-Type: application/json
Accept: application/json

{}

###

# ADD ĮDEDAMA NAUJA PREKĖ Į KREPŠELĮ
POST http://localhost:8080/sportscarshop/api/cart/1
Content-Type: application/json
Accept: application/json

{
  "id": 2,
  "qty": 100
}

###

# GET atspausdianami visi krepšeliai su prekėmis - blogai: ima atsitiktini skaičių prekių
GET http://localhost:8080/sportscarshop/api/cart/list
Accept: application/json

###

# GET atspausdianami visi krepšeliai su prekėmis
GET http://localhost:8080/sportscarshop/api/cart/1/f
Accept: application/json
Content-Type: application/json

###

# ----------------------------------------------- Cookie: JSESSIONID=...

# pirma karta paleidus sukuria nauja sesija ir atspausdina sesijos koda,
# antra - reikia nurodyti Cookie: JSESSIONID=...
POST http://localhost:8080/sportscarshop/api/cart/add
Content-Type: application/json
Accept: application/json
#Cookie: JSESSIONID=F88BAC4B2C14ADCABDBE2ADD300D4A4A

{
  "id": 1,
  "qty": 1
}

###

GET http://localhost:8080/sportscarshop/api/cart
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=4705A5639185D65213E3AAACF750C981

###

DELETE http://localhost:8080/sportscarshop/api/cart/deleteCartLine/2
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=F88BAC4B2C14ADCABDBE2ADD300D4A4A

###

PUT http://localhost:8080/sportscarshop/api/cart/updateCartLine/1/555
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=1E5F26816EBC0C1E39BF62A598FA113C

{}
###


