# Tomcat: http://localhost:8080/sportscarshop/
# App -> /api
# CartService -> /cart

# CRUD

# ADD sukuriamas tuščias krepšelis
POST http://localhost:8080/sportscarshop/api/cart
Content-Type: application/json
Accept: application/json

{}

###

# ADD ĮDEDAMA NAUJA PREKĖ Į KREPŠELĮ
POST http://localhost:8080/sportscarshop/api/cart/1
Content-Type: application/json
Accept: application/json

{
  "id": 2,
  "qty": 100
}

###

# GET atspausdianami visi krepšeliai su prekėmis
GET http://localhost:8080/sportscarshop/api/cart/list
Accept: application/json

###

# GET atspausdianami visi krepšeliai su prekėmis
GET http://localhost:8080/sportscarshop/api/cart/1/f
Accept: application/json
Content-Type: application/json

###

# ----------------------------------------------- Cookie: JSESSIONID=...

# pirma karta paleidus sukuria nauja sesija ir atspausdina sesijos koda,
# antra - reikia nurodyti Cookie: JSESSIONID=...
POST http://localhost:8080/sportscarshop/api/cart/add
Content-Type: application/json
Accept: application/json
Cookie: JSESSIONID=B1275833226CC0CAF4F5F683B01FD0FC

{
  "id": 1,
  "qty": 1
}

### jeigu tokio cart nera sukurti
POST http://localhost:8080/sportscarshop/api/cart/1
Content-Type: application/json
Accept: application/json
#Cookie: JSESSIONID=F88BAC4B2C14ADCABDBE2ADD300D4A4A

{
  "id": 1,
  "qty": 1
}

###

GET http://localhost:8080/sportscarshop/api/cart/getsessioncart
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=B1275833226CC0CAF4F5F683B01FD0FC

###

DELETE http://localhost:8080/sportscarshop/api/cart/deleteCartLine/2
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=F88BAC4B2C14ADCABDBE2ADD300D4A4A

###

PUT http://localhost:8080/sportscarshop/api/cart/updateCartLine/1/555
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=B1FF38D7886812158004BD729E143DF0

{}

###

# Mano sukurto serviso testavimas


GET http://localhost:8080/sportscarshop/api/mar/getcart/1
Accept: application/json
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoidXNlciIsInVzZXJOYW1lIjoidXNlckBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImV4cCI6MTU1NTk2MTUxOX0.3VrQ0n5kOWCC2lGvLtR2WBJ22gCYpQHZUhPhxjtWz5M

###

PUT http://localhost:8080/sportscarshop/api/mar/synchronize
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoidXNlciIsInVzZXJOYW1lIjoidXNlckBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImV4cCI6MTU1NjE4MjEyOH0.fLGAEsPYFeX6NW0Ot38OpIofa4PfsGWiI4EjfE9sK1k

###

PUT http://localhost:8080/sportscarshop/api/mar/keepusercart
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=B1275833226CC0CAF4F5F683B01FD0FC

###


