# Mano sukurto serviso testavimas

GET http://localhost:8080/sportscarshop/api/mar/getcart/1
Accept: application/json
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoidXNlciIsInVzZXJOYW1lIjoidXNlckBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImV4cCI6MTU1NTk2MTUxOX0.3VrQ0n5kOWCC2lGvLtR2WBJ22gCYpQHZUhPhxjtWz5M

###

PUT http://localhost:8080/sportscarshop/api/mar/synchronize
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoidXNlciIsInVzZXJOYW1lIjoidXNlckBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImV4cCI6MTU1NjE4MjEyOH0.fLGAEsPYFeX6NW0Ot38OpIofa4PfsGWiI4EjfE9sK1k

###

PUT http://localhost:8080/sportscarshop/api/mar/keepusercart
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=B1275833226CC0CAF4F5F683B01FD0FC

###



